# Generated by Django 5.0.6 on 2024-06-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_exam_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
